FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    wget \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file first to leverage Docker cache
COPY backend/requirements.txt .

# Install Python dependencies
RUN grep -v '^torch$' requirements.txt > req_no_torch.txt && pip install --no-cache-dir -r req_no_torch.txt

# Download Spacy model
RUN python -m spacy download en_core_web_sm

# Set default command for development
CMD ["tail", "-f", "/dev/null"]
